name: build

on:
  - push
  - pull_request

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.2
          - 5.0.0
          - 5.1.1
          - 5.2.1
          - 5.3.0



    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Deps
        run: |
          opam pin add -n h1 .
          opam pin add -n h1-lwt-unix .
          opam install -t --deps-only .

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest
